import re
import subprocess
from pathlib import Path


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
DEPENDENCY_LOCK_FILES = {
    "bun.lock",
    "bun.lockb",
    "npm-shrinkwrap.json",
    "package-lock.json",
    "Pipfile.lock",
    "pnpm-lock.yaml",
    "poetry.lock",
    "uv.lock",
    "yarn.lock",
}
GENERATED_THIRD_PARTY_FILES = {
    # Regenerated by `wrangler types`; its Cloudflare-owned documentation is
    # not first-party VMA product terminology.
    "infra/cloudflare/vma-api-router/src/worker-configuration.d.ts",
}
CJK_CHARACTER_RE = re.compile(r"[\u3400-\u4dbf\u4e00-\u9fff\uf900-\ufaff]")


def test_tracked_first_party_text_uses_organization_terminology():
    result = subprocess.run(
        ["git", "ls-files", "-z"],
        cwd=REPOSITORY_ROOT,
        check=True,
        capture_output=True,
    )
    tracked_paths = result.stdout.decode().rstrip("\0").split("\0")
    legacy_term = b"cus" + b"tomer"
    offenders: list[str] = []

    for relative_path in tracked_paths:
        path = REPOSITORY_ROOT / relative_path
        if (
            path.name in DEPENDENCY_LOCK_FILES
            or relative_path in GENERATED_THIRD_PARTY_FILES
            or not path.is_file()
        ):
            continue
        content = path.read_bytes()
        if b"\0" in content:
            continue
        for line_number, line in enumerate(content.splitlines(), start=1):
            if legacy_term in line.lower():
                offenders.append(f"{relative_path}:{line_number}")

    assert not offenders, (
        "Use explicit Organization, account, API consumer, or end-user terminology: "
        + ", ".join(offenders)
    )


def test_tracked_text_contains_no_cjk_characters():
    result = subprocess.run(
        ["git", "ls-files", "-z"],
        cwd=REPOSITORY_ROOT,
        check=True,
        capture_output=True,
    )
    tracked_paths = result.stdout.decode().rstrip("\0").split("\0")
    offenders: list[str] = []

    for relative_path in tracked_paths:
        path = REPOSITORY_ROOT / relative_path
        if not path.is_file():
            continue
        content = path.read_bytes()
        if b"\0" in content:
            continue
        for line_number, line in enumerate(
            content.decode("utf-8", errors="ignore").splitlines(),
            start=1,
        ):
            if CJK_CHARACTER_RE.search(line):
                offenders.append(f"{relative_path}:{line_number}")

    assert not offenders, "VMA tracked text must be English-only: " + ", ".join(offenders)
