from __future__ import annotations

from typing import TypeAlias

from ._client import AsyncVotrix, BinaryResponse
from ._constants import DEFAULT_BETA, SDK_VERSION
from ._exceptions import (
    APIConnectionError,
    APIResponseValidationError,
    APIStatusError,
    APIStreamError,
    APITimeoutError,
    AuthenticationError,
    BadRequestError,
    ConflictError,
    InternalServerError,
    NotFoundError,
    PermissionDeniedError,
    RateLimitError,
    UnprocessableEntityError,
    VotrixError,
)
from ._models import (
    Agent,
    ApiKey,
    ApiKeyCreated,
    ApiKeyScope,
    DeletedObject,
    Environment,
    FileObject,
    Memory,
    MemoryListItem,
    MemoryOperation,
    MemoryPrecondition,
    MemoryStore,
    MemoryVersion,
    MemoryVersionOperation,
    MemoryView,
    ModelCredential,
    ModelProvider,
    Session,
    SessionEvent,
    SessionFundingRequest,
    SessionFundingType,
    SessionResource,
    Skill,
    SkillVersion,
    UsageEntry,
    Vault,
    VotrixModel,
)
from ._pagination import AsyncPage, AsyncPaginator
from ._resources import NOT_GIVEN
from ._sse import AsyncEventStream, SSEEvent
from ._sync_client import Votrix
from ._sync_pagination import SyncPage

UsagePage: TypeAlias = AsyncPage[UsageEntry]

__version__ = SDK_VERSION

__all__ = [
    "APIConnectionError",
    "APIResponseValidationError",
    "APIStatusError",
    "APIStreamError",
    "APITimeoutError",
    "Agent",
    "ApiKey",
    "ApiKeyCreated",
    "ApiKeyScope",
    "AsyncEventStream",
    "AsyncPage",
    "AsyncPaginator",
    "AsyncVotrix",
    "AuthenticationError",
    "BadRequestError",
    "BinaryResponse",
    "ConflictError",
    "DEFAULT_BETA",
    "DeletedObject",
    "Environment",
    "FileObject",
    "InternalServerError",
    "Memory",
    "MemoryListItem",
    "MemoryOperation",
    "MemoryPrecondition",
    "MemoryStore",
    "MemoryVersion",
    "MemoryVersionOperation",
    "MemoryView",
    "ModelCredential",
    "ModelProvider",
    "NOT_GIVEN",
    "NotFoundError",
    "PermissionDeniedError",
    "RateLimitError",
    "SSEEvent",
    "Session",
    "SessionEvent",
    "SessionFundingRequest",
    "SessionFundingType",
    "SessionResource",
    "Skill",
    "SkillVersion",
    "SyncPage",
    "UnprocessableEntityError",
    "UsageEntry",
    "UsagePage",
    "Vault",
    "Votrix",
    "VotrixError",
    "VotrixModel",
    "__version__",
]
